#!/bin/bash

DEMOCA="demoCA";

if  [ -d $DEMOCA ]; then
	echo "$DEMOCA exists, remove first before setup";
else 
	echo "$DEMOCA does not exist, creating";
	mkdir $DEMOCA
	mkdir $DEMOCA/certs
	mkdir $DEMOCA/crl
	touch $DEMOCA/index.txt
	mkdir $DEMOCA/newcerts
	mkdir $DEMOCA/requests
	echo "1000" > $DEMOCA/serial
	mkdir $DEMOCA/private

	# WHAT DOES THE ABOVE DO?
	# YOUR ANSWER GOES HERE
	- first it checks if there is already a directory called demoCA and if there is it throws an error
	- if there is not: 
		- it creates the directory demoCA with subdirectories certs, crl, newcerts, requests and private.
		- it creates a file called index.txt in the demoCA directory
		- it creates a file called serial in the demoCA directory and writes "1000" to it
	  

	openssl genrsa -des3 -out $DEMOCA/private/cakey.pem 1024
	openssl req -config openssl.conf -new -x509 -days 1001 -key $DEMOCA/private/cakey.pem -out $DEMOCA/cacert.pem
	# The above does ... (high level answer expected) 
	# 
	# 	YOUR ANSWER GOES HERE
	#   - This generates a 1024 bit RSA private key that is encrypted with the des3 algorithm and stored in
	#     /demoCA/private/cakey.pem
	#   - The second command creates a self signed x509 certificate that is signed by the key created above and certified for 			1001 days and stores it in /demoCA/cacert.pm
	#
	# Look in the $DEMOCA directories and document the files that were created
	# The following files will be created in $DEMOCA
	# $DEMOCA/private/cakey.pem
	# 	YOUR DESCRIPTION OF THIS FILE BELOW, WHAT DOES IT CONTAIN, WHAT IS ITS ROLE IN THIS GAME
	# 	YOUR ANSWER GOES HERE
	# 	...
	# 
	# $DEMOCA/cacert.pem
	# 	YOUR DESCRIPTION OF THIS FILE BELOW, WHAT DOES IT CONTAIN, WHAT IS ITS ROLE IN THIS GAME
	# 	YOUR ANSWER GOES HERE
	# 	...
	# ...
	# 

	openssl x509 -in $DEMOCA/cacert.pem -noout -text
	# DOCUMENT ITS OUTPUT, DESCRIBE THE IMPORTANT PARTS OF YOUR x509 certificate
	# 
	# 	YOUR ANSWER GOES HERE
	
fi
