#!/bin/bash

DEMOCA="demoCA";

rm -fr client
mkdir client

# ANSWER MY CSR (on the assignment page, req.pem).
# TAKE IT, PLACE IT IN the $DEMOCA/requests DIRECTORY

openssl ca -config openssl.conf  -in $DEMOCA/requests/req.pem -out client/newcert.pem
# The above does ...
#
# 	YOUR ANSWER GOES HERE
#
#   - This command signs the certificate request $DEMOCA/requests/req.pem using "Haider Sajjad's"
#     information:
#          Issuer: C=CA, ST=ON, L=Mississauga, O=Internet Widgits Pty Ltd, CN=Haider Sajjad/emailAddress=haider.sajjad@mail.utoronto.ca
#   - It makes the certificate and places it in client/newcert.pem
#   - The person who requested the certificate signing is:
#          Subject: C=CA, ST=Ontario, L=Oshawa, O=Broken Leg Ltd., OU=IT, CN=cast.brokenleg.com/emailAddress=femur@brokenleg.com
#
# As in caSetup, document files created below.
# The following files will be created in ... (take a look at newcerts directory as well)
# ...
#   - client/newcert.pem

# SEND client/newcert.pem back to the requesting client, (you can email it back to me,
# but leave a copy in client (as well as the one in newcerts)

# To take a look at the new certificate...
openssl x509 -in client/newcert.pem -inform PEM -text -noout
# Certificate:
#     Data:
#         Version: 3 (0x2)
#         Serial Number: 4097 (0x1001)
#         Signature Algorithm: sha1WithRSAEncryption
#         Issuer: C = CA, ST = ON, L = Mississauga, O = Internet Widgits Pty Ltd, CN = Haider Sajjad, emailAddress = haider.sajjad@mail.utoronto.ca
#         Validity
#             Not Before: Dec  9 22:49:36 2020 GMT
#             Not After : Dec  9 22:49:36 2021 GMT
#         Subject: C = CA, ST = Ontario, L = Oshawa, O = Broken Leg Ltd., OU = IT, CN = cast.brokenleg.com, emailAddress = femur@brokenleg.com
#         Subject Public Key Info:
#             Public Key Algorithm: rsaEncryption
#                 RSA Public-Key: (1024 bit)
#                 Modulus:
#                     00:be:b4:77:41:cd:9d:3f:8a:12:12:45:0d:2a:dc:
#                     e5:8d:7f:78:b5:58:44:97:71:3d:43:bd:a1:1d:b3:
#                     45:f1:c6:5f:01:48:2e:c6:63:fa:dc:37:4e:9d:9e:
#                     f9:60:ee:9a:27:92:19:a8:62:23:8e:04:cb:0a:18:
#                     84:48:12:ea:9f:e5:41:24:5a:e3:49:36:1c:d1:81:
#                     72:46:5f:91:43:89:23:51:d1:83:91:54:f0:14:e9:
#                     fc:e6:4b:31:99:b4:f8:3c:08:71:a7:be:b5:32:41:
#                     22:f9:ec:f5:86:ba:a6:ca:bb:60:8e:75:e4:4a:8a:
#                     78:54:1e:fa:91:48:00:1a:d3
#                 Exponent: 65537 (0x10001)
#         X509v3 extensions:
#             X509v3 Basic Constraints:
#                 CA:FALSE
#             Netscape Comment:
#                 OpenSSL Generated Certificate
#             X509v3 Subject Key Identifier:
#                 9F:55:5E:D1:38:5A:40:D4:D9:3C:34:06:BA:22:87:F9:10:67:91:BF
#             X509v3 Authority Key Identifier:
#                 keyid:FF:A2:45:59:AB:C7:CC:66:97:C2:44:9E:F6:84:B6:37:A4:E7:CD:8C
#
#     Signature Algorithm: sha1WithRSAEncryption
#          89:78:47:fc:9f:a8:cc:55:ff:c9:ac:16:ce:91:1e:f3:69:b9:
#          18:42:52:54:66:6b:6e:6c:fc:e1:36:15:39:30:52:4a:36:73:
#          fc:bf:06:2f:30:f8:73:da:06:f9:be:5d:48:a4:6a:1d:44:d7:
#          b0:b7:9e:a6:11:9f:9b:36:88:bb:fa:6a:d6:37:1e:25:d9:73:
#          aa:77:b1:d5:81:ed:46:df:3b:a8:86:ca:af:1b:10:d5:cd:f6:
#          80:d7:e5:84:fa:3e:25:2e:19:78:84:97:9c:22:57:b3:cd:60:
#          76:db:bc:6b:5f:66:b4:55:2c:2c:04:75:81:0f:a7:76:2c:99:
#          6c:67

# This verifies the certificate chain
openssl verify -verbose -CAfile $DEMOCA/cacert.pem  client/newcert.pem
# client/newcert.pem: OK
